language: java
notifications:
  email: false
install: true
deploy:
  provider: releases
  api-key: 600256a1c5b19323d0a902c4e904490d1c6514d2
  file: KotH.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
matrix:
  include:
  - jdk: oraclejdk7
    script: mvn clean package