world: 'world'
enabled: true
min-players: 4
max-players: 16
secluded-chat: true
arena-time: 900
hill-clock: 60
hill-radius: 5
hill-block: beacon
score-to-win: 120
unbreakable-weapons: true
unbreakable-armor: true
friendly-fire: false
spec-on-leave: true
food-change: false
one-life: false