world: ''
enabled: true
min-players: 4
max-players: 16
secluded-chat: true
arena-time: 900
hill-clock: 60
hill-radius: 5
hill-block: bedrock
score-to-win: 150
indestructible-weapons: true
indestructible-armor: true
drop-xp: false
friendly-fire: false
food-change: false
one-life: false
change-class-in-arena: false
allow-lobby-team-change: true
circular-hill: true
drop-items: false
regen-health: true