world: ''
enabled: true
min-players: 4
max-players: 16
team-only-chat: true
secluded-chat: true
arena-time: 900
arena-auto-start: 50
hill-clock: 60
hill-radius: 5
score-to-win: 250
minimum-score: 90
indestructible-weapons: true
indestructible-armor: true
drop-xp: false
auto-respawn: true
safe-respawn-time: 3
no-spawn-camping: true
spawn-camp-distance: 4.75
friendly-fire: false
food-change: false
one-life: false
regen-health: true
classes-gui: true
change-class-in-arena: false
allow-lobby-team-change: true
circular-hill: true
drop-items: false
player-stats: true
arena-stats: true
time-tracking-cycle: 3
entry-fee: 0.00
quit-charge: $50
teleport-to-end: false
use-scoreboard: true
use-compasses: true
give-prizes: true
location-fixer: false
play-sounds: true